services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: arkjoy
      POSTGRES_PASSWORD: arkjoy
      POSTGRES_DB: arkjoy
    ports:
      - "5432:5432"
    volumes:
      - arkjoy_pg:/var/lib/postgresql/data

volumes:
  arkjoy_pg:
